export enum SystemFunction {
  setmenutitle = 0x00,
  setmenu = 0x01,
  setitem = 0x02,
  settitle = 0x03,
  setscreen = 0x04,
  setstatemachine = 0x05,
  setstate = 0x06,
  callstatemachine = 0x07,
  returnstatemachine = 0x08,
  settimer = 0x09,
  testtimer = 0x0a,
  setjobstatus = 0x0b,
  exit = 0x0c,
  exitwindows = 0x0d,
  scriptselect = 0x0e,
  scriptchange = 0x0f,
  select = 0x10,
  deselect = 0x11,
  control = 0x12,
  start = 0x13,
  stop = 0x14,
  getapistring = 0x15,
  togglelist = 0x16,
  printscreen = 0x17,
  printfile = 0x18,
  setcolor = 0x1a,
  delay = 0x1b,
  getdate = 0x1c,
  gettime = 0x1d,
  realtostring = 0x1e,
  stringtoreal = 0x1f,
  inttostring = 0x20,
  stringtoint = 0x21,
  hexconvert = 0x22,
  strcat = 0x23,
  strlen = 0x24,
  midstr = 0x25,
  realtoint = 0x26,
  inttoreal = 0x27,
  bytetoint = 0x28,
  inttolong = 0x29,
  longtoreal = 0x2a,
  PEMInitialisiere = 0x2b,
  PEMProtokollKopf = 0x2c,
  PEMProtokollZeile = 0x2d,
  PEMSGZ_Kopfzeile = 0x2e,
  PEMTrennLinie = 0x2f,
  PEMEndLinie = 0x30,
  PEMLoescheTabZeilenPuffer = 0x31,
  PEMUebertrageTabZeilenPuffer = 0x32,
  PEMProtokollAusgabe = 0x33,
  PEMDruckeEtikett = 0x34,
  PEMPrintFormular = 0x36,
  PEMPrinter_ff = 0x37,
  PEMFree_mem = 0x38,
  PEMLoad_formular = 0x39,
  PEMDefault_druckfeld = 0x3a,
  PEMDefault_besetzen = 0x3b,
  PEMForget_formular = 0x3c,
  PEMWrite_druckfeld = 0x3d,
  getinputstate = 0x3e,
  inputtext = 0x3f,
  inputnum = 0x40,
  inputhex = 0x41,
  inputdigital = 0x42,
  input2text = 0x43,
  input2hexnum = 0x44,
  input2hex = 0x45,
  inputint = 0x46,
  input2int = 0x47,
  text = 0x48,
  textout = 0x49,
  ftextout = 0x4a,
  digitalout = 0x4b,
  analogout = 0x4c,
  multianalogout = 0x4d,
  hexdump = 0x4e,
  ftextclear = 0x4f,
  clearrect = 0x50,
  blankscreen = 0x51,
  messagebox = 0x52,
  infobox = 0x53,
  userboxopen = 0x54,
  userboxclose = 0x55,
  userboxftextout = 0x56,
  userboxclear = 0x57,
  userboxsetcolor = 0x58,
  winhelp = 0x59,
  winhelpkey = 0x5a,
  callwin = 0x5b,
  viewopen = 0x5c,
  viewclose = 0x5d,
  simnum = 0x5e,
  simdigital = 0x5f,
  INPAapiInit = 0x60,
  INPAapiEnd = 0x61,
  INPAapiJob = 0x62,
  INPAapiResultText = 0x63,
  INPAapiResultInt = 0x64,
  INPAapiResultSets = 0x65,
  INPAapiResultDigital = 0x66,
  INPAapiResultAnalog = 0x67,
  INPAapiResultBinary = 0x68,
  INPAapiCheckJobStatus = 0x69,
  INPAapiFsLesen2 = 0x6a,
  INPAapiFsLesen = 0x6b,
  INPAapiFsMode = 0x6c,
  INP1apiInit = 0x6d,
  INP1apiEnd = 0x6e,
  INP1apiJob = 0x6f,
  INP1apiState = 0x70,
  INP1apiResultText = 0x71,
  INP1apiResultInt = 0x72,
  INP1apiResultSets = 0x73,
  INP1apiResultReal = 0x74,
  INP1apiResultBinary = 0x75,
  INP1apiErrorCode = 0x76,
  INP1apiErrorText = 0x77,
  GetBinaryDataString = 0x78,
  fileopen = 0x79,
  fileclose = 0x7a,
  filewrite = 0x7b,
  fileread = 0x7c,
  DTMFindLogUnit = 0x7d,
  DTMGetSGVar = 0x7e,
  DTMGetSGArt = 0x7f,
  DTMGetVarWert = 0x80,
  DTMSetupGetVarWert = 0x81,
  DTMSetupGetStartPosition = 0x82,
  DTMSetupGetNextAssoc = 0x83,
  DTMLogUnitEintragen = 0x84,
  DTMSGEintragen = 0x85,
  DTMLoescheAuftrag = 0x86,
  DTMVariableEintragen = 0x87,
  DTMVariableLoeschen = 0x88,
  DTMLoescheAlleVariablen = 0x89,
  DTMSetupVariableEintragen = 0x8a,
  DTMSetupVariableLoeschen = 0x8b,
  StrArrayCreate = 0x8c,
  StrArrayDestroy = 0x8d,
  StrArrayWrite = 0x8e,
  StrArrayRead = 0x8f,
  StrArrayGetElementCount = 0x90,
  StrArrayDelete = 0x91,
  SPSInit = 0x92,
  SPSEnd = 0x93,
  SPSLeseVonSPS = 0x94,
  SPSSendeAnSPS = 0x95,
  SPSLeseVakWerte = 0x96,
  ApiJobFsLesenFAB = 0x97,
  ApiResultFsLesenFAB = 0x98,
  ELDIOpenStartDialog = 0x99,
  CreateStructure = 0x9a,
  SetStructureMode = 0x9b,
  StructureByte = 0x9c,
  StructureInt = 0x9d,
  StructureLong = 0x9e,
  StructureString = 0x9f,
  setitemrepeat = 0xa1,
}


export const systemFunctions = [
  { id: 0x0, name: "setmenutitle", signature: "(in: string title)" },
  { id: 0x1, name: "setmenu", signature: "(in: MENU handle)" },
  { id: 0x2, name: "setitem", signature: "(in: int ItemNum, in: string ItemText, in: bool Enabled)" },
  { id: 0x3, name: "settitle", signature: "(in: string title)" },
  { id: 0x4, name: "setscreen", signature: "(in: SCREEN handle, in: bool cyclic)" },
  { id: 0x5, name: "setstatemachine", signature: "(in: STATEMACHINE handle)" },
  { id: 0x6, name: "setstate", signature: "(in: STATE handle)" },
  { id: 0x7, name: "callstatemachine", signature: "(in: STATEMACHINE handle)" },
  { id: 0x8, name: "returnstatemachine", signature: "()" },
  { id: 0x9, name: "settimer", signature: "(in: int timernum, in: int timeval)" },
  { id: 0xA, name: "testtimer", signature: "(in: int timernum, out: bool expiredflag)" },
  { id: 0xB, name: "setjobstatus", signature: "(in: int JobStatus)" },
  { id: 0xC, name: "exit", signature: "()" },
  { id: 0xD, name: "exitwindows", signature: "()" },
  { id: 0xE, name: "scriptselect", signature: "(in: string ScriptSelectIniFile)" },
  { id: 0xF, name: "scriptchange", signature: "(in: string NewScriptFile)" },
  { id: 0x10, name: "select", signature: "(in: bool MultipleSelectFlag)" },
  { id: 0x11, name: "deselect", signature: "()" },
  { id: 0x12, name: "control", signature: "()" },
  { id: 0x13, name: "start", signature: "()" },
  { id: 0x14, name: "stop", signature: "()" },
  { id: 0x15, name: "getapistring", signature: "(in: bool ArgNumFlag, in: bool FullScreenFlag, out: string ApiString)" },
  { id: 0x16, name: "togglelist", signature: "(in: bool MultipleSelectFlag, in: bool ArgNumFlag, out: string ApiToggleString)" },
  { id: 0x17, name: "printscreen", signature: "()" },
  { id: 0x18, name: "printfile", signature: "(out: int ErrorCode, in: string FileName, in: string PrinterName, in: string PrinterPort, in: bool ErrorMsgFlag)" },
  { id: 0x1A, name: "setcolor", signature: "(in: int ForeColor, in: int BackColor)" },
  { id: 0x1B, name: "delay", signature: "(in: int Time)" },
  { id: 0x1C, name: "getdate", signature: "(out: string date)" },
  { id: 0x1D, name: "gettime", signature: "(out: string time)" },
  { id: 0x1E, name: "realtostring", signature: "(in: real value, in: string format, out: string result)" },
  { id: 0x1F, name: "stringtoreal", signature: "(in: string value, out: real result)" },
  { id: 0x20, name: "inttostring", signature: "(in: int value, out: string result)" },
  { id: 0x21, name: "stringtoint", signature: "(in: string value, out: int result)" },
  { id: 0x22, name: "hexconvert", signature: "(in: string HexString, out: int high, out: int mid, out: int low, out: int seg)" },
  { id: 0x23, name: "strcat", signature: "(out: string dest, in: string left, in: string right)" },
  { id: 0x24, name: "strlen", signature: "(out: int length, in: string str)" },
  { id: 0x25, name: "midstr", signature: "(out: string result, in: string str, in: int start, in: int length)" },
  { id: 0x26, name: "realtoint", signature: "(in: real value, out: int result)" },
  { id: 0x27, name: "inttoreal", signature: "(in: int value, out: real result)" },
  { id: 0x28, name: "bytetoint", signature: "(in: byte value, out: int result)" },
  { id: 0x29, name: "inttolong", signature: "(in: int value, out: long result)" },
  { id: 0x2A, name: "longtoreal", signature: "(in: long value, out: real result)" },
  { id: 0x2B, name: "PEMInitialisiere", signature: "(out: bool Result)" },
  { id: 0x2C, name: "PEMProtokollKopf", signature: "(out: bool Result)" },
  { id: 0x2D, name: "PEMProtokollZeile", signature: "(out: bool Result)" },
  { id: 0x2E, name: "PEMSGZ_Kopfzeile", signature: "(out: bool Result)" },
  { id: 0x2F, name: "PEMTrennLinie", signature: "(out: bool Result)" },
  { id: 0x30, name: "PEMEndLinie", signature: "(out: bool Result)" },
  { id: 0x31, name: "PEMLoescheTabZeilenPuffer", signature: "(out: bool Result)" },
  { id: 0x32, name: "PEMUebertrageTabZeilenPuffer", signature: "(out: bool Result)" },
  { id: 0x33, name: "PEMProtokollAusgabe", signature: "(out: bool Result)" },
  { id: 0x34, name: "PEMDruckeEtikett", signature: "(out: bool Result)" },
  { id: 0x36, name: "PEMPrintFormular", signature: "(out: bool Result)" },
  { id: 0x37, name: "PEMPrinter_ff", signature: "(out: bool Result)" },
  { id: 0x38, name: "PEMFree_mem", signature: "(out: bool Result)" },
  { id: 0x39, name: "PEMLoad_formular", signature: "(out: bool Result)" },
  { id: 0x3A, name: "PEMDefault_druckfeld", signature: "(out: bool Result)" },
  { id: 0x3B, name: "PEMDefault_besetzen", signature: "(out: bool Result)" },
  { id: 0x3C, name: "PEMForget_formular", signature: "(out: bool Result)" },
  { id: 0x3D, name: "PEMWrite_druckfeld", signature: "(out: bool Result)" },
  { id: 0x3E, name: "getinputstate", signature: "(out: int InputState)" },
  { id: 0x3F, name: "inputtext", signature: "(out: string text, in: string Title, in: string Text)" },
  { id: 0x40, name: "inputnum", signature: "(out: real val, in: string BoxTitle, in: string BoxText, in: real minval, in: real maxval)" },
  { id: 0x41, name: "inputhex", signature: "(out: string hex, in: string Title, in: string Text, in: string Min, in: string Max)" },
  { id: 0x42, name: "inputdigital", signature: "(out: int value, in: string Title, in: string Text, in: string OffText, in: string OnText)" },
  { id: 0x43, name: "input2text", signature: "(out: string str1, out: string str2, in: string BoxTitle, in: string BoxText, in: string BoxStr1, in: string BoxStr2)" },
  { id: 0x44, name: "input2hexnum", signature: "(out: string hexstr, out: int num, in: string BoxTitle, in: string BoxText, in: string BoxStr1, in: string BoxStr2, in: string MinHexStr, in: string MaxHexStr, in: int minnum, in: int maxnum)" },
  { id: 0x45, name: "input2hex", signature: "(out: string hexstr1, out: string hexstr2, in: string BoxTitle, in: string BoxText, in: string BoxStr1, in: string BoxStr2, in: string MinHexStr1, in: string MaxHexStr1, in: string MinHexStr2, in: string MaxHexStr2)" },
  { id: 0x46, name: "inputint", signature: "(out: int value, in: string Title, in: string Text, in: int Min, in: int Max)" },
  { id: 0x47, name: "input2int", signature: "(out: int val1, out: int val2, in: string BoxTitle, in: string BoxText, in: string BoxStr1, in: string BoxStr2, in: int min1, in: int max1, in: int min2, in: int max2)" },
  { id: 0x48, name: "text", signature: "(in: int row, in: int col, in: string text)" },
  { id: 0x49, name: "textout", signature: "(in: string text, in: int row, in: int col)" },
  { id: 0x4A, name: "ftextout", signature: "(in: string text, in: int row, in: int col, in: int fontsize, in: int fontattr)" },
  { id: 0x4B, name: "digitalout", signature: "(in: bool val, in: int row, in: int col, in: string TrueText, in: string FalseText)" },
  { id: 0x4C, name: "analogout", signature: "(in: real val, in: int row, in: int col, in: real min, in: real max, in: real minvalid, in: real maxvalid, in: string format)" },
  { id: 0x4D, name: "multianalogout", signature: "(in: real val, in: int row, in: int col, in: real min, in: real max, in: real minvalid, in: real maxvalid, in: string format, in: int mode)" },
  { id: 0x4E, name: "hexdump", signature: "(in: int row, in: int col, in: string data, in: int len)" },
  { id: 0x4F, name: "ftextclear", signature: "(in: string text, in: int row, in: int col, in: int textsize, in: int textattr)" },
  { id: 0x50, name: "clearrect", signature: "(in: int row, in: int col, in: int width, in: int height)" },
  { id: 0x51, name: "blankscreen", signature: "()" },
  { id: 0x52, name: "messagebox", signature: "(in: string Title, in: string Text)" },
  { id: 0x53, name: "infobox", signature: "(in: string Title, in: string Text)" },
  { id: 0x54, name: "userboxopen", signature: "(in: int BoxNum, in: int row, in: int col, in: int height, in: int width, in: string TitleStr, in: string TextStr)" },
  { id: 0x55, name: "userboxclose", signature: "(in: int BoxNum)" },
  { id: 0x56, name: "userboxftextout", signature: "(in: int BoxNum, in: string Text, in: int Row, in: int Col, in: int ForeColor, in: int BackColor)" },
  { id: 0x57, name: "userboxclear", signature: "(in: int BoxNum)" },
  { id: 0x58, name: "userboxsetcolor", signature: "(in: int BoxNum, in: int ForeColor, in: int BackColor)" },
  { id: 0x59, name: "winhelp", signature: "(in: string helpfile)" },
  { id: 0x5A, name: "winhelpkey", signature: "(in: string helpfile, in: string key)" },
  { id: 0x5B, name: "callwin", signature: "(in: string cmdline)" },
  { id: 0x5C, name: "viewopen", signature: "(in: string FileNameStr, in: string TitleStr)" },
  { id: 0x5D, name: "viewclose", signature: "()" },
  { id: 0x5E, name: "simnum", signature: "(out: real val, in: string BoxTitle, in: string BoxText, in: real minval, in: real maxval)" },
  { id: 0x5F, name: "simdigital", signature: "(out: bool val, in: string BoxTitle, in: string BoxText, in: string FalseStr, in: string TrueStr)" },
  { id: 0x60, name: "INPAapiInit", signature: "()" },
  { id: 0x61, name: "INPAapiEnd", signature: "()" },
  { id: 0x62, name: "INPAapiJob", signature: "(in: string ecu, in: string Job, in: string Arg1, in: string Arg2)" },
  { id: 0x63, name: "INPAapiResultText", signature: "(out: string ResultText, in: string ApiResult, in: int ApiSet, in: string Format)" },
  { id: 0x64, name: "INPAapiResultInt", signature: "(out: int ResultInt, in: string ApiResult, in: int ApiSet)" },
  { id: 0x65, name: "INPAapiResultSets", signature: "(out: int sets)" },
  { id: 0x66, name: "INPAapiResultDigital", signature: "(out: bool ResultValue, in: string ApiResult, in: int ApiSet)" },
  { id: 0x67, name: "INPAapiResultAnalog", signature: "(out: real ResultValue, in: string ApiResult, in: int ApiSet)" },
  { id: 0x68, name: "INPAapiResultBinary", signature: "(in: string ApiResult, in: int ApiSet)" },
  { id: 0x69, name: "INPAapiCheckJobStatus", signature: "(in: string RefStr)" },
  { id: 0x6A, name: "INPAapiFsLesen2", signature: "(in: string ecu, in: string FileName)" },
  { id: 0x6B, name: "INPAapiFsLesen", signature: "(in: string ecu, in: string FileName)" },
  { id: 0x6C, name: "INPAapiFsMode", signature: "(in: int FsMode, in: string FsFileMode, in: string PreInfoFile, in: string PostInfoFile, in: string ApiFsJobName)" },
  { id: 0x6D, name: "INP1apiInit", signature: "(out: bool rc)" },
  { id: 0x6E, name: "INP1apiEnd", signature: "()" },
  { id: 0x6F, name: "INP1apiJob", signature: "(in: string ecu, in: string Job, in: string Arg1, in: string Arg2)" },
  { id: 0x70, name: "INP1apiState", signature: "(out: int ApiState)" },
  { id: 0x71, name: "INP1apiResultText", signature: "(out: bool rc, out: string ResultText, in: string ApiResult, in: int ApiSet, in: string Format)" },
  { id: 0x72, name: "INP1apiResultInt", signature: "(out: bool rc, out: int ResultInt, in: string ApiResult, in: int ApiSet)" },
  { id: 0x73, name: "INP1apiResultSets", signature: "(out: bool rc, out: int sets)" },
  { id: 0x74, name: "INP1apiResultReal", signature: "(out: bool rc, out: real ResultValue, in: string ApiResult, in: int ApiSet)" },
  { id: 0x75, name: "INP1apiResultBinary", signature: "(out: bool rc, in: string ApiResult, in: int ApiSet)" },
  { id: 0x76, name: "INP1apiErrorCode", signature: "(out: int ErrorCode)" },
  { id: 0x77, name: "INP1apiErrorText", signature: "(out: string ErrorText)" },
  { id: 0x78, name: "GetBinaryDataString", signature: "(out: string DataString, out: int DataStringLen)" },
  { id: 0x79, name: "fileopen", signature: "(in: string FileName, in: string OpenMode)" },
  { id: 0x7A, name: "fileclose", signature: "()" },
  { id: 0x7B, name: "filewrite", signature: "(in: string str)" },
  { id: 0x7C, name: "fileread", signature: "(out: string str, out: bool EOF)" },
  { id: 0x7D, name: "DTMFindLogUnit", signature: "(out: bool rc, in: string LogUnit)" },
  { id: 0x7E, name: "DTMGetSGVar", signature: "(out: string SGVar, in: string SGArt)" },
  { id: 0x7F, name: "DTMGetSGArt", signature: "(out: string SGArt, in: string SGVar)" },
  { id: 0x80, name: "DTMGetVarWert", signature: "(out: string VarWert, in: string VarName)" },
  { id: 0x81, name: "DTMSetupGetVarWert", signature: "(out: string VarWert, in: string VarName)" },
  { id: 0x82, name: "DTMSetupGetStartPosition", signature: "()" },
  { id: 0x83, name: "DTMSetupGetNextAssoc", signature: "(out: bool rc, inout: string VarName, inout: string VarWert)" },
  { id: 0x84, name: "DTMLogUnitEintragen", signature: "(in: string LogUnit)" },
  { id: 0x85, name: "DTMSGEintragen", signature: "(in: string SGArt, in: string SGVar)" },
  { id: 0x86, name: "DTMLoescheAuftrag", signature: "()" },
  { id: 0x87, name: "DTMVariableEintragen", signature: "(in: string VarName, in: string VarWert)" },
  { id: 0x88, name: "DTMVariableLoeschen", signature: "(out: bool rc, in: string VarName)" },
  { id: 0x89, name: "DTMLoescheAlleVariablen", signature: "()" },
  { id: 0x8A, name: "DTMSetupVariableEintragen", signature: "(in: string VarName, in: string VarWert)" },
  { id: 0x8B, name: "DTMSetupVariableLoeschen", signature: "(out: bool rc, in: string VarName)" },
  { id: 0x8C, name: "StrArrayCreate", signature: "(out: bool rc, out: int hStrArray)" },
  { id: 0x8D, name: "StrArrayDestroy", signature: "(in: int hStrArray)" },
  { id: 0x8E, name: "StrArrayWrite", signature: "(in: int hStrArray, in: int index, in: string str)" },
  { id: 0x8F, name: "StrArrayRead", signature: "(in: int hStrArray, in: int index, out: string str)" },
  { id: 0x90, name: "StrArrayGetElementCount", signature: "(in: int hStrArray, out: int ElementCount)" },
  { id: 0x91, name: "StrArrayDelete", signature: "(in: int hStrArray)" },
  { id: 0x92, name: "SPSInit", signature: "()" },
  { id: 0x93, name: "SPSEnd", signature: "()" },
  { id: 0x94, name: "SPSLeseVonSPS", signature: "(...)" },
  { id: 0x95, name: "SPSSendeAnSPS", signature: "(...)" },
  { id: 0x96, name: "SPSLeseVakWerte", signature: "(...)" },
  { id: 0x97, name: "ApiJobFsLesenFAB", signature: "(out: int rc, in: string sgvar, out: int edifehler, out: string jobstatus, out: int fehler, out: int saetze)" },
  { id: 0x98, name: "ApiResultFsLesenFAB", signature: "(out: int rc, out: int ausgeblendet, in: int satz)" },
  { id: 0x99, name: "ELDIOpenStartDialog", signature: "(in: string CommandParameter, out: int ResultCode)" },
  { id: 0x9A, name: "CreateStructure", signature: "(out: long handle, in: int length)" },
  { id: 0x9B, name: "SetStructureMode", signature: "(in: int ReadWrite)" },
  { id: 0x9C, name: "StructureByte", signature: "(in: long handle, in: int Offset, inout: byte value)" },
  { id: 0x9D, name: "StructureInt", signature: "(in: long handle, in: int Offset, inout: int value)" },
  { id: 0x9E, name: "StructureLong", signature: "(in: long handle, in: int Offset, inout: long value)" },
  { id: 0x9F, name: "StructureString", signature: "(in: long handle, in: int Offset, in: int length, inout: string value)" },
  { id: 0xA1, name: "setitemrepeat", signature: "(in: int ItemNum, in: bool Enabled)" },
];

export type SystemFunctionInfo = (typeof systemFunctions)[number];

export const SystemFunctionMap = new Map<SystemFunction, SystemFunctionInfo>(
  systemFunctions.map((fn) => [fn.id as SystemFunction, fn]),
);

