// Some utils by mikeitdone.pl
// 0 - white
int C_WHITE = 0;
// 1 - black
int C_BLACK = 1;
// 2 - grey
int C_GREY = 2;
// 3 - dark grey
int C_DARK_GREY = 3;
// 4 - red
int C_RED = 4;
// 5 - dark red
int C_DARK_RED = 5;
// 6 - magenta
int C_MAGENTA = 6;
// 7 - purple
int C_PURPLE = 7;
// 8 - yellow
int C_YELLOW = 8;
// 9 - dark yellow
int C_BROWN = 9;
// 10 - green
int C_GREEN = 10;
// 11 - dark green
int C_DARK_GREEN = 11;
// 12 - cyan
int C_CYAN = 12;
// 13 - teal
int C_TEAL = 13;
// 14 - blue
int C_BLUE = 14;
// 15 - dark blue
int C_DARK_BLUE = 15;
// -- EOF --
