import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { VitePWA } from "vite-plugin-pwa";

// Surface package.json version in the app UI without bundling the
// whole manifest. Vite's `define` replaces the identifier at build
// time, so the production bundle just contains the string literal
// (e.g. "0.3.1"). The dev server picks up changes on Vite restart.
const pkg = JSON.parse(
  readFileSync(fileURLToPath(new URL("./package.json", import.meta.url)), "utf8")
) as { version: string };

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  plugins: [
    svelte(),
    // PWA — generates a Web App Manifest, registers a service worker
    // that precaches the build output, and gives users an "install"
    // affordance on Chromium / Edge. The SW is regenerated on every
    // build, scoped to "/" (the deploy root at inpax.bimmerz.app).
    //
    // `registerType: "autoUpdate"` means new builds replace the
    // running SW silently after the next reload (no user prompt) —
    // appropriate for a sync-to-deploy diagnostic tool where stale
    // bundles can be surprising. Swap to `"prompt"` if we want a
    // user-controlled refresh later.
    //
    // `workbox.maximumFileSizeToCacheInBytes` is bumped because the
    // inpax-web bundle is currently ~750 KB minified (mostly the
    // VM + ediabasx interpreter) and Workbox's default 2 MB cap
    // would refuse to precache it on bundles that grow.
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: [
        "icon.svg",
        "favicon.ico",
        "apple-touch-icon-180x180.png",
      ],
      manifest: {
        name: "INPAX",
        short_name: "INPAX",
        description:
          "BMW INPA in the browser — run diagnostic scripts against a live ECU over Web Serial.",
        // Match the in-app accent blue (#3b82f6) so the splash screen
        // and Android theme bar pick up the brand colour.
        theme_color: "#3b82f6",
        background_color: "#ffffff",
        display: "standalone",
        start_url: "/",
        scope: "/",
        // Icon set generated by `pnpm pwa-assets` (see
        // `pwa-assets.config.ts`). Filenames must match the
        // generator's output; if you re-run the generator, update
        // this list too.
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
          { src: "icon.svg", sizes: "any", type: "image/svg+xml" },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 8 * 1024 * 1024,
        // Vite + SPA fallback so direct-URL navigation works offline.
        navigateFallback: "/index.html",
      },
    }),
  ],
  server: {
    port: 5174, // 5173 is ediabasx-web's port — sidestep so both can run
  },
  // Workspace packages compile to CommonJS-ish ESM (`tsconfig.base.json`
  // is `module: NodeNext` with no `"type": "module"` in package.jsons),
  // and Rollup's named-import analyzer trips over `Object.defineProperty`
  // exports unless we include them in `commonjsOptions`. `optimizeDeps`
  // makes Vite's dev-server pre-bundle them too so the dev/build paths
  // behave identically. Mirrors `ediabasx/apps/web/vite.config.ts`.
  optimizeDeps: {
    include: [
      "@emdzej/inpax-core",
      "@emdzej/inpax-parser",
      "@emdzej/inpax-interpreter",
      "@emdzej/inpax-dispatcher",
      "@emdzej/inpax-interfaces",
      "@emdzej/inpax-ui-provider-core",
      "@emdzej/inpax-ediabasx-provider",
      "@emdzej/inpax-ini-parser",
      "@emdzej/inpax-logger",
      "@emdzej/ediabasx-ediabas",
      // Browser-safe subpath: pulls in `GatewayClient` only, skipping
      // the gateway server (which statically requires `node:net` /
      // `node:http` / `ws` and would break the bundle). Mirrors the
      // pattern ediabasx/apps/web uses.
      "@emdzej/ediabasx-interfaces/client",
      "@emdzej/ediabasx-interface-base",
      "@emdzej/ediabasx-interface-serial",
    ],
  },
  build: {
    commonjsOptions: {
      include: [/node_modules/, /packages\//],
      transformMixedEsModules: true,
    },
  },
});
